---
- name: enable ufw
  ufw:
    state: enabled

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    enabled: yes

- name: restart ssh
  systemd:
    name: ssh
    state: restarted
