---
# Environment-based Ansible Inventory
# Values are populated from environment variables or script parameters

all:
  hosts:
    production-server:
      ansible_host: "{{ lookup('env', 'VPS_HOST') }}"
      ansible_user: "{{ lookup('env', 'VPS_USER') | default('root') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_PRIVATE_KEY_FILE') }}"
      domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"
      ssl_email: "{{ lookup('env', 'SSL_EMAIL') | default('admin@' + lookup('env', 'DOMAIN_NAME')) }}"
      git_repo_url: "{{ lookup('env', 'GIT_REPO_URL') }}"
      git_branch: "{{ lookup('env', 'GIT_BRANCH') | default('main') }}"

  vars:
    # Application settings
    app_name: "{{ lookup('env', 'APP_NAME') | default('nestjs-blog-api') }}"
    app_port: "{{ lookup('env', 'APP_PORT') | default('3000') }}"
    app_user: "{{ lookup('env', 'APP_USER') | default('deploy') }}"
    app_dir: '/opt/{{ app_name }}'

    # Database settings
    postgres_db: "{{ lookup('env', 'POSTGRES_DB') | default('blog_db') }}"
    postgres_user: "{{ lookup('env', 'POSTGRES_USER') | default('blog_user') }}"
    postgres_version: "{{ lookup('env', 'POSTGRES_VERSION') | default('15') }}"

    # Redis settings
    redis_port: "{{ lookup('env', 'REDIS_PORT') | default('6379') }}"

    # Docker settings
    docker_compose_version: "{{ lookup('env', 'DOCKER_COMPOSE_VERSION') | default('2.21.0') }}"

    # SSL/TLS settings
    use_ssl: "{{ lookup('env', 'USE_SSL') | default('true') | bool }}"
    ssl_provider: "{{ lookup('env', 'SSL_PROVIDER') | default('letsencrypt') }}"

    # Environment
    environment: "{{ lookup('env', 'ENVIRONMENT') | default('production') }}"

    # Git settings
    git_repo_url: git@github.com:yourusername/blog-api.git
    git_branch: main
