all:
  children:
    production:
      hosts:
        prod-server:
          ansible_host: YOUR_VPS_IP_HERE
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          domain_name: yourdomain.com
          ssl_email: your-email@example.com

    staging:
      hosts:
        staging-server:
          ansible_host: YOUR_STAGING_IP_HERE
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          domain_name: staging.yourdomain.com
          ssl_email: your-email@example.com

  vars:
    # Application settings
    app_name: nestjs-blog-api
    app_port: 3000
    app_user: deploy
    app_dir: /opt/{{ app_name }}

    # Database settings
    postgres_db: blog_db
    postgres_user: blog_user
    postgres_version: '15'

    # Redis settings
    redis_port: 6379

    # Docker settings
    docker_compose_version: '2.21.0'

    # SSL/TLS settings
    use_ssl: true
    ssl_provider: letsencrypt
