---
- name: Install snapd
  package:
    name: snapd
    state: present

- name: Install certbot via snap
  snap:
    name: certbot
    classic: yes
  when: use_ssl and ssl_provider == "letsencrypt"

- name: Create certbot symlink
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
  when: use_ssl and ssl_provider == "letsencrypt"

- name: Stop nginx for certificate generation
  shell: |
    cd {{ app_dir }}
    docker-compose -f docker-compose.prod.yml stop nginx
  become_user: '{{ app_user }}'
  when: use_ssl and ssl_provider == "letsencrypt"

- name: Generate Let's Encrypt certificate
  shell: |
    certbot certonly --standalone \
    --non-interactive \
    --agree-tos \
    --email {{ ssl_email }} \
    -d {{ domain_name }}
  when: use_ssl and ssl_provider == "letsencrypt"

- name: Copy SSL certificates to application directory
  shell: |
    cp /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem {{ app_dir }}/docker/ssl/
    cp /etc/letsencrypt/live/{{ domain_name }}/privkey.pem {{ app_dir }}/docker/ssl/
    chown {{ app_user }}:{{ app_user }} {{ app_dir }}/docker/ssl/*.pem
  when: use_ssl and ssl_provider == "letsencrypt"

- name: Start nginx with SSL certificates
  shell: |
    cd {{ app_dir }}
    docker-compose -f docker-compose.prod.yml up -d nginx
  become_user: '{{ app_user }}'
  when: use_ssl and ssl_provider == "letsencrypt"

- name: Create certificate renewal script
  copy:
    content: |
      #!/bin/bash
      certbot renew --quiet
      cp /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem {{ app_dir }}/docker/ssl/
      cp /etc/letsencrypt/live/{{ domain_name }}/privkey.pem {{ app_dir }}/docker/ssl/
      chown {{ app_user }}:{{ app_user }} {{ app_dir }}/docker/ssl/*.pem
      cd {{ app_dir }}
      docker-compose -f docker-compose.prod.yml restart nginx
    dest: /usr/local/bin/renew-ssl.sh
    mode: '0755'
  when: use_ssl and ssl_provider == "letsencrypt"

- name: Setup SSL certificate renewal cron job
  cron:
    name: 'Renew SSL certificates'
    minute: '0'
    hour: '2'
    job: '/usr/local/bin/renew-ssl.sh'
  when: use_ssl and ssl_provider == "letsencrypt"
