name: Database Migration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      migration_type:
        description: 'Migration type'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - reset
          - seed
      confirm_reset:
        description: 'DANGER: Type "CONFIRM" to reset database'
        required: false
        type: string

jobs:
  migrate:
    name: Database Migration - ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate reset confirmation
        if: github.event.inputs.migration_type == 'reset'
        run: |
          if [ "${{ github.event.inputs.confirm_reset }}" != "CONFIRM" ]; then
            echo "❌ Database reset requires confirmation!"
            echo "Please type 'CONFIRM' in the confirm_reset field"
            exit 1
          fi
          echo "⚠️ Database reset confirmed for ${{ github.event.inputs.environment }}"

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          if [ "${{ github.event.inputs.environment }}" == "production" ]; then
            ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts
          else
            ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts
          fi

      - name: Run database migration
        run: |
          if [ "${{ github.event.inputs.environment }}" == "production" ]; then
            HOST="${{ secrets.PRODUCTION_HOST }}"
            USER="${{ secrets.PRODUCTION_USER }}"
          else
            HOST="${{ secrets.STAGING_HOST }}"
            USER="${{ secrets.STAGING_USER }}"
          fi

          case "${{ github.event.inputs.migration_type }}" in
            "deploy")
              echo "🚀 Running database migrations..."
              ssh $USER@$HOST "cd /opt/nestjs-blog-api && docker-compose -f docker-compose.prod.yml exec -T app npx prisma migrate deploy"
              ;;
            "reset")
              echo "⚠️ RESETTING DATABASE..."
              ssh $USER@$HOST "cd /opt/nestjs-blog-api && docker-compose -f docker-compose.prod.yml exec -T app npx prisma migrate reset --force"
              ;;
            "seed")
              echo "🌱 Seeding database..."
              ssh $USER@$HOST "cd /opt/nestjs-blog-api && docker-compose -f docker-compose.prod.yml exec -T app npx prisma db seed"
              ;;
          esac

      - name: Verify database status
        run: |
          if [ "${{ github.event.inputs.environment }}" == "production" ]; then
            HOST="${{ secrets.PRODUCTION_HOST }}"
            USER="${{ secrets.PRODUCTION_USER }}"
          else
            HOST="${{ secrets.STAGING_HOST }}"
            USER="${{ secrets.STAGING_USER }}"
          fi

          echo "🔍 Checking database status..."
          ssh $USER@$HOST "cd /opt/nestjs-blog-api && docker-compose -f docker-compose.prod.yml exec -T app npx prisma migrate status"

      - name: Migration summary
        run: |
          echo "📊 Migration Summary:"
          echo "- Environment: ${{ github.event.inputs.environment }}"
          echo "- Migration Type: ${{ github.event.inputs.migration_type }}"
          echo "- Timestamp: $(date -u)"
          echo "✅ Migration completed successfully!"
