name: Database Migration

on:
  workflow_dispatch:
    inputs:
      migration_type:
        description: 'Migration type'
        required: true
        default: 'deploy'
        type: choice
        options:
          - deploy
          - reset
          - seed
      confirm_reset:
        description: 'DANGER: Type "CONFIRM" to reset database'
        required: false
        type: string

jobs:
  migrate:
    name: Database Migration - Production
    runs-on: ubuntu-latest
    # environment: production  # Uncomment when GitHub environment is configured

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate reset confirmation
        if: github.event.inputs.migration_type == 'reset'
        run: |
          if [ "${{ github.event.inputs.confirm_reset }}" != "CONFIRM" ]; then
            echo "❌ Database reset requires confirmation!"
            echo "Please type 'CONFIRM' in the confirm_reset field"
            exit 1
          fi
          echo "⚠️ Database reset confirmed for production"

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts

      - name: Run database migration
        run: |
          case "${{ github.event.inputs.migration_type }}" in
            "deploy")
              echo "🚀 Running database migrations..."
              ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd /opt/nestjs-blog-api && docker-compose -f docker-compose.prod.yml exec -T app npx prisma migrate deploy"
              ;;
            "reset")
              echo "⚠️ RESETTING DATABASE..."
              ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd /opt/nestjs-blog-api && docker-compose -f docker-compose.prod.yml exec -T app npx prisma migrate reset --force"
              ;;
            "seed")
              echo "🌱 Seeding database..."
              ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd /opt/nestjs-blog-api && docker-compose -f docker-compose.prod.yml exec -T app npx prisma db seed"
              ;;
          esac

      - name: Verify database status
        run: |
          echo "🔍 Checking database status..."
          ssh ${{ secrets.PRODUCTION_USER }}@${{ secrets.PRODUCTION_HOST }} "cd /opt/nestjs-blog-api && docker-compose -f docker-compose.prod.yml exec -T app npx prisma migrate status"

      - name: Migration summary
        run: |
          echo "📊 Migration Summary:"
          echo "- Environment: Production"
          echo "- Migration Type: ${{ github.event.inputs.migration_type }}"
          echo "- Timestamp: $(date -u)"
          echo "✅ Migration completed successfully!"
