name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch/Tag to deploy'
        required: true
        default: 'main'
        type: string
      force_deploy:
        description: 'Force deployment (skip health checks)'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '18'
  PNPM_VERSION: '8'

jobs:
  manual-deploy:
    name: Manual Deploy to Production
    runs-on: ubuntu-latest
    # environment: production  # Uncomment when GitHub environment is configured

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Validate inputs
        run: |
          echo "🚀 Deploying to: Production"
          echo "📝 Branch/Tag: ${{ github.event.inputs.branch }}"
          echo "⚡ Force deploy: ${{ github.event.inputs.force_deploy }}"

      - name: Setup Python for Ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PRODUCTION_HOST }} >> ~/.ssh/known_hosts

      - name: Create Ansible inventory
        run: |
          mkdir -p /tmp/ansible
          cat > /tmp/ansible/hosts.yml << EOF
          ---
          all:
            hosts:
              production-server:
                ansible_host: ${{ secrets.PRODUCTION_HOST }}
                ansible_user: ${{ secrets.PRODUCTION_USER }}
                ansible_ssh_private_key_file: ~/.ssh/id_rsa
                domain_name: ${{ secrets.PRODUCTION_DOMAIN }}
                ssl_email: ${{ secrets.SSL_EMAIL }}
                git_repo_url: ${{ github.server_url }}/${{ github.repository }}
                git_branch: ${{ github.event.inputs.branch }}
                
            vars:
              app_name: nestjs-blog-api
              app_port: 3000
              app_user: deploy
              app_dir: /opt/nestjs-blog-api
              postgres_db: blog_db
              postgres_user: blog_user
              postgres_version: "15"
              redis_port: 6379
              docker_compose_version: "2.21.0"
              use_ssl: true
              ssl_provider: letsencrypt
          EOF

      - name: Pre-deployment health check
        if: ${{ !github.event.inputs.force_deploy }}
        run: |
          echo "🔍 Checking current application health..."
          if curl -f -s "https://${{ secrets.PRODUCTION_DOMAIN }}/health" > /dev/null; then
            echo "✅ Application is currently healthy"
          else
            echo "⚠️ Application health check failed - proceeding with deployment"
          fi

      - name: Deploy application
        run: |
          cd infrastructure/ansible
          echo "🚀 Starting deployment..."
          ANSIBLE_ROLES_PATH=./roles ansible-playbook -i /tmp/ansible/hosts.yml playbooks/update.yml -v
        env:
          ANSIBLE_HOST_KEY_CHECKING: False

      - name: Post-deployment verification
        run: |
          echo "⏳ Waiting for application to start..."
          sleep 30

          echo "🔍 Verifying deployment..."
          if curl -f -s "https://${{ secrets.PRODUCTION_DOMAIN }}/health" > /dev/null; then
            echo "✅ Deployment successful! Application is healthy."
            echo "🌐 Application URL: https://${{ secrets.PRODUCTION_DOMAIN }}"
          else
            echo "❌ Deployment verification failed!"
            echo "🔗 Please check: https://${{ secrets.PRODUCTION_DOMAIN }}/health"
            exit 1
          fi

      - name: Deployment summary
        if: always()
        run: |
          echo "📊 Deployment Summary:"
          echo "- Environment: Production"
          echo "- Branch/Tag: ${{ github.event.inputs.branch }}"
          echo "- Commit: ${{ github.sha }}"
          echo "- Application URL: https://${{ secrets.PRODUCTION_DOMAIN }}"
          echo "- Health Check: https://${{ secrets.PRODUCTION_DOMAIN }}/health"
          echo "- API Documentation: https://${{ secrets.PRODUCTION_DOMAIN }}/api"
